name:                haskell-wordle
version:             0.1.0.0
github:              "githubuser/haskell-wordle"
license:             BSD3
author:              "Pratap Singh"
maintainer:          "pratap at pratap dot dev"
copyright:           "2022 Pratap Singh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-wordle#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- MonadRandom

library:
  source-dirs: src

executables:
  haskell-wordle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-wordle

tests:
  haskell-wordle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-wordle
